import {
  CalendarIcon,
  ChevronIcon,
  CloseIcon,
  DropletIcon,
  EditIcon,
  FilmTextIcon,
  FilterIcon,
  FolderIcon,
  LayersIcon,
  LogoutIcon,
  MapIcon,
  SearchIcon,
  SettingsIcon,
  SortIcon,
  TimeIcon,
  UserIcon,
  VideoIcon,
} from './icons'

export const Icons = {
  Calendar: CalendarIcon,
  Chevron: ChevronIcon,
  Close: CloseIcon,
  Droplet: DropletIcon,
  Edit: EditIcon,
  FilmText: FilmTextIcon,
  Filter: FilterIcon,
  Folder: FolderIcon,
  Layers: LayersIcon,
  Logout: LogoutIcon,
  Map: MapIcon,
  Search: SearchIcon,
  Settings: SettingsIcon,
  Sort: SortIcon,
  Time: TimeIcon,
  User: UserIcon,
  Video: VideoIcon,
}
